# Generated by Django 5.1.6 on 2025-03-28 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0002_producto_precio_producto_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='fecha_creacion',
            field=models.DateField(null=True),
        ),
    ]
