# Generated by Django 5.1.6 on 2025-04-07 04:14

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IfoExtra',
            new_name='InfoExtra',
        ),
    ]
